### ISSUE TITLE
URL Scheme does not seem to work.

### ISSUE THREAD

**Issue by TuckerLonginotti** [Esri/arcgis-appstudio-samples#10]
I have customized a version of Survey123 in Appstudio and configured the URL Scheme with "suu".
 
![capture2](https://cloud.githubusercontent.com/assets/15017826/22128467/f8656b6c-de5d-11e6-81f9-8f75fc6a7341.JPG)

 
I have then side loaded my app on my iphone and it works perfectly, well almost.
 
To my understanding I just need to replace 'arcgis-survey123' with 'suu'.  However, when I click the link it gets stuck in the image >>
![img_00562](https://cloud.githubusercontent.com/assets/15017826/22128698/26eb8d9e-de5f-11e6-83b7-b936cde48ba5.png)

  What am I missing?
 
arcgis-survey123://?itemID=89bc8c7844e548e09baa3aad4695e78b&field:AssetID=FF34001&field:Status=Good&center=43.567,-117.380
 
suu://?itemID=89bc8c7844e548e09baa3aad4695e78b&field:AssetID=FF34001&field:Status=Good&center=43.567,-117.380
 
 
 
Note:  when I save the link does break and gets replaced with #?itemid=...... However, I am able to crack open the json and change it back to the suu://?itemID= as shown above.
 
Also, when I copy and paste the link into safari manually it does redirect to my custom Survey123 app and open it.  It just doesn't work from Collector 10.4.2 on iOS 10.2.
 
Any Suggestions?
 
Thanks.

**Comment by sathyaprasad** [comment]
Due to an iOS 10 issue custom url schemes needed to be added explicitly in the app manifest. Check with the latest 2.0 release and post any comments you have on the Survey123 or AppStudio geonet community where more folks are actively watching.
