### ISSUE TITLE
Basemap Picker problem!!

### ISSUE THREAD

**Issue by albavoli** [Esri/arcgis-appstudio-samples#7]
i have a problem when i use as a basemap this url
http://services.arcgisonline.com/ArcGIS/rest/services/ESRI_StreetMap_World_2D/MapServer
the function is not working at all.Can u help me with this??

**Comment by spatialdude** [comment]
The problem is the spatial reference of that service is **4326**. Survey123 only supports basemap services that are in the web mercator projection.

**Comment by albavoli** [comment]
But i need to use that url for the routing so there is no chance that basemap picker works with this url ??

**Comment by spatialdude** [comment]
No. Base maps must be in web mercator. The existing built-in world street map service is essentially the same data in web mercator project i.e. http://www.arcgis.com/home/item.html?id=3b93337983e9436f8db950e38a8629af

**Comment by albavoli** [comment]
Thanks for the answer
